esphome:
  name: cryingplants

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

network:
  enable_ipv6: true

openthread:
  tlv: "yours here"

output:
"

output:
  - platform: gpio
    pin: GPIO15
    id: onboard_led

  - platform: gpio
    pin: 
      number: GPIO8
      inverted: true
    id: sensor_power_gpio

light:
  - platform: binary
    name: "FireBeetle Thread LED"
    output: onboard_led

switch:
  - platform: output
    name: "CryingPlants Sensor Power GPIO8"
    output: sensor_power_gpio
    id: sensor_power

sensor:
  - platform: adc
    pin: GPIO0
    name: "CryingPlants Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    update_interval: 30s
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - multiply: 2.0

  - platform: adc
    pin: GPIO2
    name: "CryingPlants Soil Sensor 1 Raw"
    id: soil_sensor_1_raw
    attenuation: 12db
    update_interval: 10s
    accuracy_decimals: 3
    unit_of_measurement: "V"

