esphome:
  name: cryingplants
  on_boot:
    priority: -100
    then:
      - delay: 10s
      - component.update: battery_voltage
      - switch.turn_on: sensor_power
      - delay: 2s
      - component.update: sensor1
      - component.update: sensor2
      - component.update: sensor3
      - component.update: sensor4
      - delay: 1s
      - switch.turn_off: sensor_power

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

network:
  enable_ipv6: true

openthread:
  tlv: "yours here"
deep_sleep:
  id: deep_sleep_control
  run_duration: 60s
  sleep_duration: 60s

output:
  - platform: gpio
    pin: GPIO15
    id: onboard_led

  - platform: gpio
    pin:
      number: GPIO8
      inverted: true
    id: sensor_power_gpio

light:
  - platform: binary
    name: "FireBeetle Thread LED"
    output: onboard_led

switch:
  - platform: output
    name: "Sensor Power"
    output: sensor_power_gpio
    id: sensor_power

script:
  - id: perform_measurement
    then:
      - switch.turn_on: sensor_power
      - delay: 2s
      - component.update: sensor1
      - component.update: sensor2
      - component.update: sensor3
      - component.update: sensor4
      - delay: 1s
      - switch.turn_off: sensor_power

button:
  - platform: template
    name: "Measure Now"
    id: measure_now
    on_press:
      - script.execute: perform_measurement

sensor:
  - platform: adc
    pin: GPIO0
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    update_interval: 30s
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage
    state_class: measurement
    filters:
      - multiply: 2.0

  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      float v = id(battery_voltage).state;

      if (isnan(v))
        return NAN;

      float pct = (v - 3.30f) / (4.20f - 3.30f) * 100.0f;

      if (pct > 100.0f) pct = 100.0f;
      if (pct < 0.0f) pct = 0.0f;

      return pct;

  - platform: adc
    pin: GPIO2
    name: "Sensor1"
    id: sensor1
    attenuation: 12db
    update_interval: never
    unit_of_measurement: "V"
    accuracy_decimals: 3

  - platform: adc
    pin: GPIO3
    name: "Sensor2"
    id: sensor2
    attenuation: 12db
    update_interval: never
    unit_of_measurement: "V"
    accuracy_decimals: 3

  - platform: adc
    pin: GPIO4
    name: "Sensor3"
    id: sensor3
    attenuation: 12db
    update_interval: never
    unit_of_measurement: "V"
    accuracy_decimals: 3

  - platform: adc
    pin: GPIO5
    name: "Sensor4"
    id: sensor4
    attenuation: 12db
    update_interval: never
    unit_of_measurement: "V"
    accuracy_decimals: 3


