esphome:
  name: cryingplants

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

network:
  enable_ipv6: true

openthread:
tlv: "yours here"

output:

output:
  - platform: gpio
    pin: GPIO15
    id: onboard_led

light:
  - platform: binary
    name: "FireBeetle Thread LED"
    output: onboard_led
